"""Machine-learning model for phishing detection.

The :class:`PhishingModel` wraps a scikit-learn ``GradientBoostingClassifier``
trained on a synthetic dataset derived from real-world phishing-pattern
research.  The synthetic dataset was generated by combining documented
phishing indicators (see feature modules) and adding realistic noise.

The model is **re-trainable**: callers may supply labelled feature vectors
via :meth:`PhishingModel.fit` to adapt the detector to a specific
deployment environment.

Model persistence is handled by :func:`joblib.dump` / :func:`joblib.load`.
"""

from __future__ import annotations

import logging
import os
import pathlib
from typing import Dict, List, Optional, Sequence, Tuple

import joblib
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Feature column order – must match the order used during training and
# during inference in detector.py
# ---------------------------------------------------------------------------
URL_FEATURES: List[str] = [
    "url_uses_ip",
    "url_is_long",
    "url_has_at_sign",
    "url_double_slash_redirect",
    "url_has_dash_in_domain",
    "url_subdomain_count",
    "url_is_http",
    "url_suspicious_tld",
    "url_is_shortener",
    "url_suspicious_keywords",
    "url_brand_impersonation",
    "url_path_depth",
    "url_query_complexity",
    "url_encoded_chars",
]

TEXT_FEATURES: List[str] = [
    "text_urgency",
    "text_credential_request",
    "text_threat_language",
    "text_oci_keywords",
    "text_deceptive_phrases",
    "text_html_risks",
    "text_url_count",
    "text_external_link_ratio",
    "text_obfuscation",
    "text_all_caps_ratio",
]

HEADER_FEATURES: List[str] = [
    "header_from_display_mismatch",
    "header_reply_to_differs",
    "header_return_path_mismatch",
    "header_subject_urgency",
    "header_subject_credential_lure",
    "header_subject_oci_lure",
    "header_spoofed_high_value_domain",
    "header_suspicious_received",
    "header_missing_message_id",
    "header_html_only",
]

ALL_FEATURES: List[str] = URL_FEATURES + TEXT_FEATURES + HEADER_FEATURES


def _build_pipeline() -> Pipeline:
    return Pipeline(
        [
            ("scaler", StandardScaler()),
            (
                "clf",
                GradientBoostingClassifier(
                    n_estimators=120,
                    max_depth=4,
                    learning_rate=0.1,
                    subsample=0.8,
                    random_state=42,
                ),
            ),
        ]
    )


def _generate_synthetic_data(
    n_samples: int = 2000, random_state: int = 42
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate a synthetic labelled dataset based on known phishing patterns.

    The dataset is **not** a substitute for real-world data; it establishes
    reasonable default decision boundaries that can be refined via
    :meth:`PhishingModel.fit`.

    Returns:
        (X, y) where X has shape ``(n_samples, len(ALL_FEATURES))`` and
        y contains binary labels (1 = phishing, 0 = legitimate).
    """
    rng = np.random.default_rng(random_state)
    n_feat = len(ALL_FEATURES)
    half = n_samples // 2

    # ------------------------------------------------------------------
    # Legitimate samples – low feature scores with Gaussian noise
    # ------------------------------------------------------------------
    legit_means = np.zeros(n_feat)
    legit_stds = np.ones(n_feat) * 0.12
    X_legit = rng.normal(legit_means, legit_stds, (half, n_feat))
    # Clamp to [0, 1]
    X_legit = np.clip(X_legit, 0, 1)

    # ------------------------------------------------------------------
    # Phishing samples – higher base scores for indicative features
    # ------------------------------------------------------------------
    phish_means = np.zeros(n_feat)
    # URL-based indicators
    for feat in [
        "url_uses_ip",
        "url_suspicious_tld",
        "url_is_shortener",
        "url_brand_impersonation",
        "url_suspicious_keywords",
        "url_has_at_sign",
        "url_is_http",
        "url_subdomain_count",
    ]:
        idx = ALL_FEATURES.index(feat)
        phish_means[idx] = 0.70

    # Text-based indicators
    for feat in [
        "text_urgency",
        "text_credential_request",
        "text_threat_language",
        "text_deceptive_phrases",
    ]:
        idx = ALL_FEATURES.index(feat)
        phish_means[idx] = 0.65

    # Header-based indicators
    for feat in [
        "header_from_display_mismatch",
        "header_reply_to_differs",
        "header_spoofed_high_value_domain",
        "header_subject_urgency",
        "header_subject_credential_lure",
    ]:
        idx = ALL_FEATURES.index(feat)
        phish_means[idx] = 0.68

    phish_stds = np.ones(n_feat) * 0.18
    X_phish = rng.normal(phish_means, phish_stds, (n_samples - half, n_feat))
    X_phish = np.clip(X_phish, 0, 1)

    X = np.vstack([X_legit, X_phish])
    y = np.array([0] * half + [1] * (n_samples - half))

    # Shuffle
    idx = rng.permutation(n_samples)
    return X[idx], y[idx]


class PhishingModel:
    """Gradient-boosted classifier for phishing detection.

    Args:
        model_path: Optional path to a pre-saved model file.  If the file
            exists it is loaded; otherwise a default model trained on
            synthetic data is used.
    """

    def __init__(self, model_path: Optional[str] = None) -> None:
        self._pipeline: Optional[Pipeline] = None
        self._feature_names: List[str] = ALL_FEATURES

        if model_path and os.path.exists(model_path):
            self.load(model_path)
            logger.info("Loaded model from %s", model_path)
        else:
            self._train_default()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def predict(self, features: Dict[str, float]) -> Tuple[int, float]:
        """Classify a single sample described by *features*.

        Args:
            features: Mapping of feature name → score.  Missing keys are
                filled with ``0.0``.

        Returns:
            ``(label, probability)`` where *label* is 1 (phishing) or
            0 (legitimate) and *probability* is the classifier's
            confidence in the phishing class.
        """
        X = self._features_to_array(features)
        label: int = int(self._pipeline.predict(X)[0])
        prob: float = float(self._pipeline.predict_proba(X)[0][1])
        return label, prob

    def fit(
        self,
        feature_dicts: Sequence[Dict[str, float]],
        labels: Sequence[int],
    ) -> None:
        """Retrain the model on caller-supplied data.

        Args:
            feature_dicts: Sequence of feature dictionaries (one per sample).
            labels: Binary labels – 1 for phishing, 0 for legitimate.
        """
        X = np.array([self._dict_to_row(d) for d in feature_dicts])
        y = np.array(labels)
        self._pipeline = _build_pipeline()
        self._pipeline.fit(X, y)
        logger.info("Model retrained on %d samples.", len(labels))

    def save(self, path: str) -> None:
        """Persist the trained pipeline to *path* using joblib."""
        pathlib.Path(path).parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self._pipeline, path)
        logger.info("Model saved to %s", path)

    def load(self, path: str) -> None:
        """Load a previously saved pipeline from *path*."""
        self._pipeline = joblib.load(path)

    @property
    def feature_names(self) -> List[str]:
        """Ordered list of feature names expected by the model."""
        return list(self._feature_names)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _train_default(self) -> None:
        """Train on the built-in synthetic dataset."""
        X, y = _generate_synthetic_data()
        self._pipeline = _build_pipeline()
        self._pipeline.fit(X, y)
        logger.debug("Default model trained on %d synthetic samples.", len(y))

    def _dict_to_row(self, features: Dict[str, float]) -> np.ndarray:
        return np.array([features.get(f, 0.0) for f in self._feature_names])

    def _features_to_array(self, features: Dict[str, float]) -> np.ndarray:
        return self._dict_to_row(features).reshape(1, -1)
